src/qgis_geonode/apiclient/api_client.py
Work for https://github.com/kartoza/qgis_geonode/issues/1
Use cases that have been covered in this PR
@ricardogsilva I could not find API endpoint in the GeoNode v2 API that directly provide layer's metadata fields and an endpoint that provides layer's default styles.
=> More support for the  GeoNode v2 API

.github/workflows/main.yml
This PR adds an initial github actions workflow for having Continuous Integration in this repo.
The proposed implementation just adds a linting step whereby [black](https://github.com/psf/black) is used to check the format of the code.
The proposed implementation uses the official QGIS docker image as a base container for running the workflow steps. This means that in the short term we will be able to expand on it to run automated tests
fixes #16
=> 16 add initial GitHub actions workflow for ci

README.md, pluginadmin.py, poetry.lock, pyproject.toml, test/conftest.py
This PR refactors the way in which we work with the QGIS Python bindings in the poetry-generated virtualenv. 
It removes the vext.pyqt5 and adds a function to symlink external qgis python bindings and its PyQt5 and sip dependencies. This is exposed in the `pluginadmin.py` CLI and can be used as:
```python
poetry run python pluginadmin.py install-qgis-into-venv
```
=> Refactor how we use qgis python bindings inside the poetry venv

.github/workflows/docs.yml, docs/about.md, docs/index.md, docs/user-guide.md, mkdocs.yml, poetry.lock, pyproject.toml
This PR adds an initial skeleton for the plugin documentation website. It uses mkdocs as a base.
for now there isn't much content. This is mainly to have it in place when the time to add great docs comes.
fixes #33
=> Add skeleton for the documentation website

poetry.lock, pyproject.toml, test/conftest.py, test/test_apiclient.py
Changed the poetry python version limit from 3.8 to 3.6 and added "importlib-metadata" package in the dependencies file, this
will be needed when using python 3.6.
These changes will enable to use the project in a system environment where python 3.6 is the support version eg Ubuntu 18.04, this has been largely influence by the use of QGIS in the project tests.
=> Update on python version and packages

src/qgis_geonode/api_client.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/search_result_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/56
This PR adds functionality for loading the GeoNode layer search results as QGIS layers.
It would have been nice if we could determine from API layer response if the search result layers types so as to know whether to enable or disable the "WFS"/"WCS" buttons, at the moment there is no way to know about the layer type.
=> Load GeoNode layers into QGIS

src/qgis_geonode/api_client.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py
Populating QGIS layer loaded from the Geonode provider with metadata from GeoNode.
fixes #57 
fixes #76
=> Adding metadata into the QGIS layer

src/qgis_geonode/ui/search_result_widget.ui
The search result widget was making the scroll area expand when any of the search result title or description are long, this is because there were no word wrapping setting in the title and description. This PR adds word wrap setting on the corresponding items.
Related to #66
=> Added word wrapping on search result widget

src/qgis_geonode/api_client.py, test/_mock_geonode.py, test/_mock_geonode_data/layer_list_filtered_response1.json, test/_mock_geonode_data/map_list_filtered_response1.json, test/test_apiclient.py
Fixes https://github.com/kartoza/qgis_geonode/issues/29
Adds support in the API client for using search filters on the GeoNode V2 API. The added tests are only covering the equality operation for filtering.
The logic for creating filtering query strings is left for API client users(GUI).
=> Adding search filtering in the API client

src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/search_result_widget.ui
This PR implements loading a GeoNode resource's thumbnail and showing it the QGIS search results section, as depicted in the screenshot below:
fixes #65
=> Show layer thumbnails on search results page

src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/search_result_widget.ui
This PR adds some small improvements to the resource search page, namely:
- resource title is now bigger
- abstract is aligned to top
- resource type is now shown
=> Make resource title bigger and add resource type

src/qgis_geonode/api_client.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/geonode_datasource_widget.ui, src/qgis_geonode/utils.py
Fixes https://github.com/kartoza/qgis_geonode/issues/80
Adds search filtering via GUI, now it searches using all the field items except start, end and spatial extent items.
The current search filtering doesn't support filtering with more than one field, The free text is treated as a title when filtering, abstract will be included once a better way of filtering two different fields has been
devised.
The search filter items UI is updated to included checkboxes that will allow user to later have options about which items they want to include in filtering resources.
This PR also adds fetching of all keywords in the GeoNode instance using endpoint '/h_keywords_api'.
Screenshot
=> Support for search filtering in the GUI

src/qgis_geonode/apiclient/apiv2.py, src/qgis_geonode/apiclient/csw.py, src/qgis_geonode/apiclient/models.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/search_result_widget.ui, test/test_apiclient_csw.py
Fixes https://github.com/kartoza/qgis_geonode/issues/67
Creates on the fly the OGC related buttons for loading layer from search result items, this enables to create and load only required buttons for each search item as search item can have different resource types.
=> Dynamically creating layer loading buttons for search items

src/qgis_geonode/gui/layer_properties_config_widget.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/qgis_geonode_layer_dialog.ui, src/qgis_geonode/ui/search_result_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/58
Connects the "Open in Browser" button in the plugin custom widget available in the layer properties to open the layer GeoNode detail page in the default browser.
Screenshot
=> Open GeoNode layer page from the layer properties

src/qgis_geonode/apiclient/apiv2.py, src/qgis_geonode/apiclient/csw.py, src/qgis_geonode/conf.py, src/qgis_geonode/gui/connection_dialog.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/connection_dialog.ui, test/test_apiclient_csw.py
This PR implements initial support for private layers when using the GeoNode CSW endpoints.
GeoNode's CSW endpoint is not protected with OAuth2, it uses the browser session. This is likely a bug in GeoNode, as CSW is supposed to be a machine-machine interface and therefore is not likely to be accessed via browser. Regardless, since we need to support existing GeoNode deployments, this PR introduces a working solution, if not very elegant.
When using the CSW API for searching and retrieving records we perform a login to the main GeoNode GUI, emulating a browser. Upon login we receive the `sessionid` cookie, which is then included in subsequent requests. In order to be able to perform the login, we need to be given the  `username` and `password` by the user. This means that this type of …
=> 98 geonode csw interface uses session auth

src/qgis_geonode/apiclient/apiv2.py, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/csw.py, src/qgis_geonode/apiclient/models.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/geonode_datasource_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/63
Adds ordering parameter in the GeonodeClient backend and new UI items to support ordering when searching for resources.
Currently the implementation works on only the "name" field, when using others fields including "title" and "abstract" the search results into a "ProtocolInvalidError".
=> Support for ordering when searching resources

src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/ui/geonode_datasource_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/138
Now storing the search buttons state each time they change, and when there is no selected resource type we just disable all of them(at this moment we are not storing their state) and when there is at least one selected resource type we restore the search buttons states.
=> Improved search buttons state update logic

src/qgis_geonode/gui/connection_dialog.py
Previous implementation compared the current name against itself (if the connection was being edited) and resulted in unwanted changes to the connection name.
fixes #130
=> Fix incorrect name checking

CHANGELOG.md, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/geonode_datasource_widget.ui, src/qgis_geonode/utils.py
This PR implements:
1. A tighter control over the availability of search UI controls. Most UI controls are now disabled when a search or load operation is in course. This prevents the user from putting the UI in an invalid state
2. Improved error handling and reporting. Also, the message bar no longer causes the other widgets to jump around whenever it is shown/hidden
3. Asynchronous loading of GeoNode layers onto the QGIS canvas. These were previously being loaded in the same thread as the UI, which caused undesirable blocking. Layers are now loaded on a background thread, by leveraging QgsTask
fixes #138 
fixes #69
=> Fix search button state

src/qgis_geonode/apiclient/apiv2.py, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/csw.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/ui/geonode_datasource_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/123
Using start and end datetime inputs in the search group box, this PR adds support for temporal filtering using those inputs.
The filtering use a range that include a start datetime and doesn't include the end datetime. The API uses 'date' field (store timestamp of when the resource was created) field to filter resources.
=> Support for temporal filtering

src/qgis_geonode/ui/search_result_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/126
=> Make resource title and type in the search widget selectable

src/qgis_geonode/gui/connection_dialog.py, src/qgis_geonode/ui/connection_dialog.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/70
Adds progress bar in the message bar, using the same approach used in the main widget to add the progress message when searching or loading resources.
=> Add progress message when testing connection

src/qgis_geonode/gui/search_result_widget.py
When handling errors from layer loading, this PR make the http status code and reason parameters optional, some errors might occur from QGIS process loading of layer and will have no http status code or reason.
This PR contains changes from https://github.com/kartoza/qgis_geonode/pull/156
=> Small handling error handling update

src/qgis_geonode/apiclient/csw.py
Fixes https://github.com/kartoza/qgis_geonode/issues/140
Since `title` from CSW layer detail can differ from `title` on the API v1 layer detail, this PR replace the `title` with `alternate` property, the `alternate` seems to always contains the same value with `name` from the CSW record. `typename` field seem more fit for the use but it is not filterable while `alternate` is filterable.
=> Change property to used to fetch layer detail from API v1

CHANGELOG.md, pyproject.toml
This PR increases the minimum QGIS version to 3.18.
We need this as the minimum since the plugin is making use of a custom section on the layer properties dialog. Support for this for layers of type raster has been added as of QGIS v 3.18
fixes #187
=> Bump QGIS minimum version to 3.18

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/version_postv2.py, src/qgis_geonode/gui/geonode_map_layer_config_widget.py, src/qgis_geonode/gui/search_result_widget.py, src/qgis_geonode/metadata.py, src/qgis_geonode/network.py, src/qgis_geonode/ui/qgis_geonode_layer_dialog.ui
This PR implements loading and saving some metadata fields of a QGIS layer to the corresponding GeoNode dataset.
Implementation is similar to how #185 allowed saving/loading styles back to GeoNode. For now, uploading metadata back to GeoNode is restricted to:
- `title`
- `abstract`
fixes #189
=> Implement update of metadata fields

src/qgis_geonode/main.py
This PR remove the empty reference to the plugin in QGIS' plugins menu
fixes #180
=> Remove empty reference to the plugin in QGIS plugins menu

CHANGELOG.md, poetry.lock, pyproject.toml, src/qgis_geonode/apiclient/version_postv2.py
This PR implements export of a layer's style via SLD and subsequent upload to GeoNode. This way, when creating a new GeoNode dataset from QGIS it will include the QGIS style too
fixes #194
=> Export and upload SLD file with layer style

CHANGELOG.md, README.md, src/qgis_geonode/apiclient/__init__.py, src/qgis_geonode/conf.py, src/qgis_geonode/gui/connection_dialog.py, src/qgis_geonode/gui/geonode_data_source_widget.py, src/qgis_geonode/network.py, src/qgis_geonode/vendor/README.md, src/qgis_geonode/vendor/packaging/LICENSE, src/qgis_geonode/vendor/packaging/LICENSE.APACHE, src/qgis_geonode/vendor/packaging/LICENSE.BSD, src/qgis_geonode/vendor/packaging/__about__.py, src/qgis_geonode/vendor/packaging/__init__.py, src/qgis_geonode/vendor/packaging/_structures.py, src/qgis_geonode/vendor/packaging/version.py
This PR swaps out the custom API discoverer task with the common network task used elsewhere in the codebase.
This ensures that connection testing uses auth credentials (when available) and also makes the code a bot more coherent.
Also included is initial work for #190, as we are now leaning on GeoNode's `/version.txt` endpoint in order to get the concrete GeoNode version.
fixes #186
=> 186 connection test should use authentication

CHANGELOG.md, src/qgis_geonode/apiclient/geonode_v3.py, src/qgis_geonode/gui/search_result_widget.py
This PR fixes a recent regression whereby a dataset's abstract was no longer being shown on the search results listing
fixes #206
=> Fix dataset abstract not being shown on the search results

.github/workflows/ci.yml, .github/workflows/rebuild-docs.yml, .github/workflows/release.yml, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/geonode_v3.py, src/qgis_geonode/apiclient/models.py, src/qgis_geonode/gui/geonode_map_layer_config_widget.py, test/test_apiclient_geonode_v3.py
This PR improves compatibility with GeoNode 3.3.x and also fixes a problem whereby re-downloading layer metadata was not working OK.
It also adds some unit tests 
fixes #208 
fixes #199 
fixes #210
=> Improve compatibility with GeoNode 3.3.1

src/qgis_geonode/apiclient/geonode_v3.py, src/qgis_geonode/network.py
This type annotation got introduced in Python 3.8 and we are supporting Python 3.7 (which is used on OSGEO4W)
fixes #213
=> Remove usage of the typing.Final type annotation

CHANGELOG.md, src/qgis_geonode/apiclient/geonode_v3.py, src/qgis_geonode/apiclient/legacy.py, src/qgis_geonode/apiclient/models.py, test/test_apiclient_geonode_v3.py
This PR fixes a couple of bugs:
- Always provide a known value for dataset types, even when nothing is reported by the remote GeoNode. In this case we assign `GeonodeResourceType.UNKNOWN`
- Do not use f-string debug formatting in the form `f"{some_variable=}"` as this is not supported on Python 3.7, which is still the target version of Python for OSGEO4W
=> Fix possibly empty dataset type

docs/user-guide.md
This PR simply moves the OAuth2 auth section to a collapsible block in order to make it clearer that this option is not recommended.
fixes #233
=> De-emphasize OAuth2 as an authorization connection method

CHANGELOG.md, src/qgis_geonode/gui/geonode_data_source_widget.py
This PR improves the automatic focus of the main `Search` button in the QGIS data source manager dialogue.
Additionally, it also sets the focus on the `title` line edit right after a search has ended. It would also be nice to make this widget gain focus automatically when the dialog is opened (or the plugin tab is selected by the user) but that does not seem to be possible, as there does not seem to be a way to let the plugin run code after the dialogue is shown
fixes #230
=> Improve widget focus behavior on main search dialog

CHANGELOG.md, src/qgis_geonode/conf.py, src/qgis_geonode/gui/geonode_data_source_widget.py
This PR fixes a bug where the plugin was trying to parse the GeoNode version even when it had been previously set to `network.UNSUPPORTED_REMOTE` and subsequently failed.
The proposed implementation does a stricter check and even disables the `search` button if the current connection is known not to be valid
fixes #231
=> Do not try to parse GeoNode version when we know the connection URL is not valid

CHANGELOG.md, src/qgis_geonode/gui/geonode_data_source_widget.py, src/qgis_geonode/ui/geonode_datasource_widget.ui
This PR fixes a bug that manifested after initial installation of the plugin. If there was no current connection, the plugin would crash.
fixes #243
=> Fix first usage crash due to there not being a current connection

CHANGELOG.md, pyproject.toml, src/qgis_geonode/gui/connection_dialog.py
This PR implements default selection of WFS version 1.1.0 on the new connection dialog. This shall ensure that by default the plugin is configured to use a WFS version which is known to work OK also for performing WFS editing.
fixes #244
=> make sure default wfs version is 1.1.0

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/gui/connection_dialog.py
If a url is copied from the browser from a GeoNode instance e.g., https://stable.demo.geonode.org/#/ it contains an a hash sign at the end which fails to connect. This fixes the issue by parsing the provided url.
This PR fixes [issue 274](https://github.com/GeoNode/QGISGeoNodePlugin/issues/274).
=> Fixed connection error when base url with '#' is provided as the connection url

src/qgis_geonode/styles.py
The style string is being decoded as 'utf-8' from the hex encoding. Changing the decoding to 'latin-1' gets rid of the 'UnicodeDecodeError for umlaut characters.
Here is the  [related issue](https://github.com/GeoNode/QGISGeoNodePlugin/issues/248).
=> Fixed encoding issues for characters with umlaut

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/geonode_api_v2.py, src/qgis_geonode/gui/geonode_map_layer_config_widget.py
This PR solves the `keyError: 'url'` which reported in the following [issue](https://github.com/GeoNode/QGISGeoNodePlugin/issues/263).
=> KeyError: 'url' during layer upload to GeoNode

src/qgis_geonode/conf.py, src/qgis_geonode/gui/connection_dialog.py, src/qgis_geonode/gui/geonode_data_source_widget.py, src/qgis_geonode/main.py, src/qgis_geonode/ui/connection_dialog.ui
This PR provides some UI improvements according to this [issue](https://github.com/GeoNode/QGISGeoNodePlugin/issues/286)
=> UI improvements in the connection dialog

src/qgis_geonode/conf.py, src/qgis_geonode/gui/geonode_map_layer_config_widget.py, src/qgis_geonode/main.py
This PR fixes the error of after the reload a default style or metadata from GeoNode in the `layer properties` dialog, reported in the issue #285 
Also, it was implemented a more elegant way to find the QDialog object,  in order using its `syncToLayer` method to synchronize the current changes from the plugin with the layer properties dialog.
=> Fix the error after the reload a default style or metadata from GeoNode

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/geonode_api_v2.py, src/qgis_geonode/gui/geonode_map_layer_config_widget.py, src/qgis_geonode/gui/search_result_widget.py
This PR solves the error of 
```bash
Unable to load layer <some layer>: None
```
according to this issue #281
=> Fixing in the loading layer failure through WFS

src/qgis_geonode/styles.py, src/qgis_geonode/utils.py
This PR fixes the issue #297 .
It adds a function `remove_comments_from_sld` which remove all the  comments from the retrieved SLD because if the SLD includes comments, QGIS crashes during serialization.
=> QGIS crashes during the loading of SLD

poetry.lock, pyproject.toml, src/qgis_geonode/gui/search_result_widget.py
This PR solves the issue #299 . When the user was trying to add a layer from a different SRID (e.g EPSG 2100), the final layer extent was set using the coordinates of WGS 84 (EPSG 4326). As a result the layer could not be found by using the `zoom to layer` option.
To solve this issue, I set the layer extent using the `spatial_extent` of the layer (which is well defined) right before the layer is added to the map.
=> Setting the extent of the layer using the defined spatial_extent before adding to the map

src/qgis_geonode/apiclient/geonode_api_v2.py, src/qgis_geonode/utils.py, test/test_apiclient_geonode_api_v2.py
This PR fixes the issue #259 . It includes a function which re-formats the URLs from GeoServer including services (`gs/ows`) and SLD.
=> [Fixes ISSUE 259] Loading of dataset fails if domain contains geoserver
