ui/qgis_geonode_connection.ui, ui/qgis_geonode_layer_dialog.ui, ui/qgis_geonode_main_ui.ui, ui/qgis_geonode_searched_resource.ui
=> skeleton ui

geonode_api/api_client.py, geonode_api/layer.py, geonode_api/maps.py
=> Geonode API sketch

src/qgis_geonode/apiclient/api_client.py
This PR adds an initial implementation of an asynchronous GeoNode API client based on [QgsNetworkContentFetcher](https://qgis.org/api/classQgsNetworkContentFetcherTask.html).
Here is an example usage, which you can try from within QGIS' python console:
```python
from qgis_geonode.apiclient.api_client import GeonodeClient
def show_contents(contents):
print(contents)
c1 = GeonodeClient("https://master.demo.geonode.org/")
c1.layer_list_received.connect(show_contents)
c1.get_layers()
```
The proposed implementation suggests that further development of the `GeonodeClient` class will add methods for the other GeoNode API endpoints (e.g. `self.get_layer_details(layer_id)`). These additional methods shall spawn instances of `QgsNetworkContentFetcher` tasks, which will asynchronously interact with …
=> Add initial code for a GeoNode API client

src/qgis_geonode/apiclient/api_client.py
=> Support paging in fetching layer list

src/qgis_geonode/apiclient/api_client.py
=> Paging maps list from API

src/qgis_geonode/gui/layer_properties_config_widget.py, src/qgis_geonode/qgisgeonode/main.py, src/qgis_geonode/qgisgeonode/utils.py
=> support for hooking into QGIS layer properties dialog

README.md, src/qgis_geonode/__init__.py, src/qgis_geonode/apiclient/api_client.py, src/qgis_geonode/apiclient/layer.py, src/qgis_geonode/apiclient/maps.py, src/qgis_geonode/gui/layer_properties_config_widget.py, src/qgis_geonode/qgisgeonode/Qgis_GeoNode_dockwidget.py, src/qgis_geonode/qgisgeonode/main.py, src/qgis_geonode/qgisgeonode/utils.py
This shall hopefully make the newly introduced CI workflow pass for the first time!
=> Apply automated code formatting with black

.github/workflows/main.yml
Add pull_request as an additional event to listen to for triggering github action workflow
fixes #35
=> fix github action workflows not running on pull requests

.github/workflows/release.yml, mkdocs.yml, pluginadmin.py, poetry.lock, pyproject.toml
This PR adds an initial implementation of a workflow to automate publishing new versions of the plugin whenever a new tag is created
fixes #32
=> Add initial automation of plugin repo

.gitignore, docs/index.md, mkdocs.yml
This PR is mainly about documentation.
- Adds some links to the project's source code
- Does some initial tweaking of the documentation site's settings
fixes #41
=> Add links to repo and docs and customize docs site a bit

src/qgis_geonode/apiclient/api_client.py
Update to remove variable which was used only once in one of the API client functions.
=> Minor code changes

.github/workflows/ci.yml, poetry.lock, pyproject.toml, test/test_apiclient.py
=> Add automated tests to the CI pipeline

README.md, docs/development.md, docs/index.md, mkdocs.yml
=> Add documentation for development and release procedures

README.md, docs/about.md, docs/development.md, docs/index.md, mkdocs.yml
This PR fixes some incorrect URLs in the docs.
It also adds some badges and some text to the doc sections.
=> Fix some docs typos and restructure a bit

CHANGELOG.md, README.md, docs/user-guide.md, pyproject.toml
=> Add missing metadata and small fixes to docs

.github/workflows/ci.yml, .pre-commit-config.yaml, pluginadmin.py, pyproject.toml, test/conftest.py, test/test_apiclient.py
This allows using pre-commit (https://pre-commit.com/) with the plugin repo
=> Add pre-commit config file

pluginadmin.py
This PR modifies the generation of the custom QGIS plugin repo so that only the latest release from either `stable` or `experimental` type is shown
fixes #83
=> generate custom plugin repo xml file with only the current releases

src/qgis_geonode/apiclient/apiv2.py, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/csw.py, src/qgis_geonode/apiclient/models.py, src/qgis_geonode/conf.py, src/qgis_geonode/gui/connection_dialog.py, src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/ui/connection_dialog.ui, test/test_apiclient.py
This PR adds a new `page size` setting to each connection and uses it to fetch list results.
fixes #86
=> Add page_size as a new connection setting

docs/development.md, docs/index.md
=> Updated installation docs

src/qgis_geonode/conf.py, src/qgis_geonode/gui/connection_dialog.py, src/qgis_geonode/gui/geonode_source_select_provider.py
This PR refactors the way we handle selection of connections in the GUI in order to overcome the existing bugs.
fixes #111 
fixes #101
=> Fix connection selection in the GUI

src/qgis_geonode/ui/geonode_datasource_widget.ui
Also removed the unused Add/Close buttons on the main search UI
fixes #110
fixes #133
=> Move Title search filter outside of the collapsible group box.

pluginadmin.py, src/qgis_geonode/gui/geonode_source_select_provider.py
=> Reset pagination whenever user initiates a new search

src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/gui/search_result_widget.py
Screenshot
fixes #113 
fixes #81 
fixes #100
=> Feedback to user when fetching resources

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/csw.py, src/qgis_geonode/gui/search_result_widget.py
Fixes https://github.com/kartoza/qgis_geonode/issues/141
Now each time error is raised when loading layers, the CSW API emits an error_received signal, then the UI code updates the interface.
=> Restore UI to normal state after an error occurs

src/qgis_geonode/gui/search_result_widget.py
Use correct variable for the layer URI
=> Minor variable name fix

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/gui/geonode_source_select_provider.py
Clicking the toolbox button beside keywords combo box result into an error, see below screenshot
This PR returns the support for keywords searching in the plugin which was available at some point back.
=> Fix on keywords fetching

src/qgis_geonode/gui/geonode_source_select_provider.py, src/qgis_geonode/ui/geonode_datasource_widget.ui
Fixes https://github.com/kartoza/qgis_geonode/issues/161
Screenshot
=> Add keyword tool button icon and tooltip

src/qgis_geonode/apiclient/apiv2.py, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/models.py, src/qgis_geonode/utils.py
This PR makes the code a bit more robust to errors that may arise when retrieving a list of remote datasets
=> Improve error handling when getting layer list from remote GeoNode

src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/geonode_v3.py, src/qgis_geonode/apiclient/legacy.py
This PR fixes a recent regression with trying to parse a dataset's SLD when it may not have been downloaded
fixes #203
=> Fix trying to parse SLD that has not been downloaded

src/qgis_geonode/gui/geonode_map_layer_config_widget.py
=> Don't try to create a geonode API client for non GeoNode layers

pyproject.toml, src/qgis_geonode/network.py
This does not exist on QGIS3.18, which is our current target
=> remove QgsNetworkAccessManager.authBrowserAborted

CHANGELOG.md, src/qgis_geonode/gui/geonode_map_layer_config_widget.py, src/qgis_geonode/network.py
=> do not use ElementTree's xml_declaration

CHANGELOG.md, docs/index.md, mkdocs.yml
=> Update docs to reflect publication on official QGIS plugin repo

src/qgis_geonode/apiclient/geonode_v3.py
When using the GeoNode proxy to GeoServer we need to ensure we are referring to the GeoNode base URL and not whatever URL is GeoServer's base
fixes #227
=> Use GeoNode base URL when replacing service URLs

docs/index.md, src/qgis_geonode/gui/geonode_data_source_widget.py
This PR replaces the core QGIS GeoNode provider with this plugin in the QGIS GUI - WIP
fixes #229
=> Replace core GeoNode provider with the plugin

CHANGELOG.md, src/qgis_geonode/apiclient/base.py, src/qgis_geonode/apiclient/geonode_v3.py, src/qgis_geonode/apiclient/legacy.py, src/qgis_geonode/apiclient/models.py, src/qgis_geonode/gui/geonode_map_layer_config_widget.py, src/qgis_geonode/gui/search_result_widget.py
This PR implements selectively hiding or disabling UI controls depending on the permissions reported by the remote GeoNode.
fixes #235
=> Hide UI controls if user does not have permission to perform action

src/qgis_geonode/gui/geonode_data_source_widget.py
=> [Fixes #255] fix core provider replacemente

src/qgis_geonode/ui/search_result_widget.ui
Thumbnails's size fix after searching
=> Thumbnails's size fix after searching

src/qgis_geonode/gui/search_result_widget.py
This PR solves the bug of #302
=> fixing s bug regarding the SLD request failure
